name: Build and Publish to PyPI

on:
  release:
    types: [published]

jobs:
  PypI-Release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    
    - name: Build Package
      run:
        python3 pip install --upgrade pip build
        python3 build

    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TESTPYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/